version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  persona:
    build: ./person_service
    depends_on:
      - rabbitmq

  cuenta:
    build: ./account_service
    depends_on:
      - rabbitmq
